### ISSUE TITLE
Use UCSB EFC Calculator Libraries?

### ISSUE THREAD

**Issue by loganfranken** [soulshake/fafsahacker#4]
Hey there!

Not sure if this project is still under development?

If so: at the University of California, Santa Barbara, we've created a couple implementations of the Expected Family Contribution (EFC) calculation (both in .NET and PHP):
https://github.com/ucsbfinaid

For a project like this, it might be helpful to just use the UCSB implementation of the Federal calculation and add features on top of it.

If there's anything we could do to make the libraries easier to consume, please let us know!

**Comment by soulshake** [comment]
Hi @loganfranken, sorry, I totally missed this. Will take a look!

**Comment by loganfranken** [comment]
No need to be sorry: if you decide to use the libraries, definitely let me know what we can do to make the libraries easier for you to use!
